### ISSUE TITLE
New notification changes existing notifications' position

### ISSUE THREAD

**Issue by thenoobtester** [r0-zero/phyOS-dunst#3]
Hi,

thank you for this, I also wanted to be able to change the notification's location on the fly per app. However when I create a notification, say at top-left and before it exits I create another at top-right the old one is moved to top-right so I guest it's not really multiple window dunst we have here right? Or is this a bug?

I guess multiple window dunst would be more complex because you would have to keep track of the different windows and add the new notifications to the window corresponding to their location if one exists, here it just moves the whole window from one location to the other, which is better than nothing.

Thank you for this again.

**Comment by FT-Labs** [comment]
Unfortunately there is one window :( Only dynamic positions. I'm really over my head of creating multiple distros, picom and pdwm, I really dont have time for anything else now :( . After some time maybe, but lets just hope dunst maintainers implement this feature, because its really complex.

**Comment by thenoobtester** [comment]
Sure, they always claimed it was a complex thing to do. But thanks for this though it's still useful to me :)
